definitions:
  steps:
    - step: &build
        name: Build static files
        image: node:16.15.0-slim
        caches:
          - node
        script:
          - echo 'Running NPM Install'
          - npm install
          - rm -rf .next out # Remove built directories from previous builds (prevent EEXIST error)
          - echo 'Running NPM RUN EXPORT'
          - npm run export
        variables:
          NODE_ENV: 'production'
        artifacts:
          - out/**

    - step: &deploy
        name: Deploy
        script:
          - echo  'Deploying to:' $DEPLOYMENT_ENVIRONMENT
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
              APP_LOCATION: '$BITBUCKET_CLONE_DIR/out'
              OUTPUT_LOCATION: ''
              API_TOKEN: $deployment_token
              DEPLOYMENT_ENVIRONMENT: $DEPLOYMENT_ENVIRONMENT
              SKIP_APP_BUILD: 'true'
              SKIP_API_BUILD: 'true'

    - step: &deployBucket
        name: Deploy_Bucket
        script:
          - echo  'Deploying to:' $DEPLOYMENT_ENVIRONMENT
          - pipe: atlassian/azure-storage-deploy:1.0.2
            variables:
              SOURCE: '$BITBUCKET_CLONE_DIR/out/*'
              DESTINATION: 'https://ommwebmedia.blob.core.windows.net/\\\$web/activity22/dev'
              DESTINATION_SAS_TOKEN: $AZURE_STORAGE_SAS_TOKEN
pipelines:
  default:
    - step:
        <<: *build
  branches:
    'develop':
      - step:
          <<: *build
      - step:
          <<: *deploy
          deployment: dev
    'main':
      - step:
          <<: *build
      - step:
          <<: *deploy
          deployment: staging
  tags:
    release-*:
      - step:
          <<: *build
      - step:
          <<: *deploy
          deployment: production
          trigger: manual
